document.addEventListener('DOMContentLoaded', () => {
  const $ = (selector) => document.querySelector(selector);
  const state = { documents: [], selectedId: null, document: null, dirty: false };
  const ui = { loading: $('#studio-loading'), empty: $('#studio-empty'), workspace: $('#studio-workspace'), notice: $('#studio-notice'), dialog: $('#document-dialog'), list: $('#document-list') };
  const escapeHtml = (value) => { const el = document.createElement('div'); el.textContent = value ?? ''; return el.innerHTML; };
  async function request(url, options) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (response.status === 401) { location.replace('/login'); throw new Error('Your session has ended.'); } if (!response.ok) throw new Error(data.error || 'Something went wrong.'); return data; }
  function notify(message) { ui.notice.textContent = message; ui.notice.hidden = !message; }
  function setSaveState(message) { $('#save-state').textContent = message || ''; }
  function formatDate(value) { return value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : ''; }
  function openDialog() { $('#document-error').hidden = true; $('#document-form').reset(); ui.dialog.showModal(); }
  function listDocuments() { ui.list.innerHTML = state.documents.map((document) => `<button class="document-item ${document.id === state.selectedId ? 'active' : ''}" data-id="${document.id}" type="button"><strong>${escapeHtml(document.title)}</strong><span>${escapeHtml(document.status)} · ${formatDate(document.updated_at)}</span></button>`).join(''); }
  async function loadDocuments(preferredId) { const data = await request('/api/content-studio/documents'); state.documents = data.documents; ui.loading.hidden = true; if (!state.documents.length) { ui.empty.hidden = false; ui.workspace.hidden = true; return; } ui.empty.hidden = true; ui.workspace.hidden = false; state.selectedId = Number(preferredId) || state.selectedId || state.documents[0].id; if (!state.documents.some((document) => document.id === state.selectedId)) state.selectedId = state.documents[0].id; listDocuments(); await loadDocument(); }
  async function loadDocument() { const data = await request(`/api/content-studio/documents/${state.selectedId}`); state.document = data.document; state.dirty = false; renderDocument(); }
  function bullets(value, target) { $(target).innerHTML = value ? value.split('\n').filter(Boolean).map((item) => `<li>${escapeHtml(item.replace(/^\d+\.\s*/, ''))}</li>`).join('') : '<li>Generate a starter draft to get guidance.</li>'; }
  function renderDocument() { const document = state.document; $('#document-label').textContent = `Version ${document.version} · ${document.status}`; $('#document-status').value = document.status; $('#document-title').value = document.title; $('#document-brand').textContent = document.brand_name; $('#document-type').textContent = document.content_type; $('#document-keyword').textContent = document.keyword; $('#document-tone').textContent = `${document.tone} tone`; $('#seo-title').value = document.seo_title; $('#meta-description').value = document.meta_description; $('#document-content').value = document.content; bullets(document.outline, '#document-outline'); bullets(document.recommendations, '#document-recommendations'); setSaveState(`Saved ${formatDate(document.updated_at)}`); }
  function markDirty() { state.dirty = true; setSaveState('Unsaved changes'); }
  function editorPayload() { return { title: $('#document-title').value, content: $('#document-content').value, seo_title: $('#seo-title').value, meta_description: $('#meta-description').value, status: $('#document-status').value }; }
  async function saveDocument() { if (!state.document) return; const button = $('#save-document'); button.disabled = true; button.textContent = 'Saving…'; try { const data = await request(`/api/content-studio/documents/${state.document.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editorPayload()) }); state.document = data.document; state.dirty = false; renderDocument(); await loadDocuments(state.document.id); } catch (error) { notify(error.message); } finally { button.disabled = false; button.textContent = 'Save changes'; } }
  async function generateDocument() { if (state.dirty && !confirm('Generate a new starter draft? Unsaved edits will be replaced.')) return; const button = $('#generate-document'); button.disabled = true; button.textContent = 'Generating…'; notify(''); try { const data = await request(`/api/content-studio/documents/${state.document.id}/generate`, { method: 'POST' }); state.document = data.document; state.dirty = false; renderDocument(); await loadDocuments(state.document.id); } catch (error) { notify(error.message); } finally { button.disabled = false; button.textContent = 'Generate starter draft'; } }
  $('#open-document-dialog').addEventListener('click', openDialog); $('#empty-new-document').addEventListener('click', openDialog); $('#library-new-document').addEventListener('click', openDialog); $('#close-document-dialog').addEventListener('click', () => ui.dialog.close());
  $('#document-form').addEventListener('submit', async (event) => { event.preventDefault(); const button = $('#save-new-document'); const error = $('#document-error'); button.disabled = true; button.textContent = 'Creating…'; error.hidden = true; try { const data = await request('/api/content-studio/documents', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); ui.dialog.close(); await loadDocuments(data.document.id); } catch (err) { error.textContent = err.message; error.hidden = false; } finally { button.disabled = false; button.textContent = 'Create content brief'; } });
  ui.list.addEventListener('click', (event) => { const item = event.target.closest('[data-id]'); if (!item || Number(item.dataset.id) === state.selectedId) return; if (state.dirty && !confirm('Discard unsaved changes and open another document?')) return; state.selectedId = Number(item.dataset.id); loadDocument().then(listDocuments).catch((error) => notify(error.message)); });
  ['#document-title', '#seo-title', '#meta-description', '#document-content', '#document-status'].forEach((selector) => $(selector).addEventListener('input', markDirty)); $('#document-status').addEventListener('change', markDirty); $('#save-document').addEventListener('click', saveDocument); $('#generate-document').addEventListener('click', generateDocument);
  $('#delete-document').addEventListener('click', async () => { if (!state.document || !confirm(`Delete “${state.document.title}”? This cannot be undone.`)) return; try { await request(`/api/content-studio/documents/${state.document.id}`, { method: 'DELETE' }); state.selectedId = null; state.document = null; await loadDocuments(); } catch (error) { notify(error.message); } });
  $('#logout-button').addEventListener('click', () => request('/api/logout', { method: 'POST' }).then(() => location.assign('/')).catch((error) => notify(error.message)));
  loadDocuments().catch((error) => { ui.loading.hidden = true; notify(error.message); });
});
