document.addEventListener('DOMContentLoaded', () => {
  const $ = (selector) => document.querySelector(selector);
  const state = { collections: [], selectedId: null, report: null };
  const ui = { loading: $('#prompt-loading'), empty: $('#collection-empty'), workspace: $('#prompt-workspace'), picker: $('#collection-picker'), notice: $('#prompt-notice'), dialog: $('#collection-dialog') };
  const escapeHtml = (value) => { const el = document.createElement('div'); el.textContent = value ?? ''; return el.innerHTML; };
  async function request(url, options) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (response.status === 401) { location.replace('/login'); throw new Error('Your session has ended.'); } if (!response.ok) throw new Error(data.error || 'Something went wrong.'); return data; }
  function notify(message) { ui.notice.textContent = message; ui.notice.hidden = !message; }
  function openDialog() { $('#collection-error').hidden = true; $('#collection-form').reset(); ui.dialog.showModal(); }
  function renderCollections() { ui.picker.innerHTML = state.collections.map((collection) => `<option value="${collection.id}">${escapeHtml(collection.name)} · ${escapeHtml(collection.brand_name)}</option>`).join(''); ui.picker.value = state.selectedId; }
  async function loadCollections(preferredId) { const data = await request('/api/prompt-intelligence/collections'); state.collections = data.collections; ui.loading.hidden = true; if (!state.collections.length) { ui.empty.hidden = false; ui.workspace.hidden = true; return; } ui.empty.hidden = true; ui.workspace.hidden = false; state.selectedId = Number(preferredId) || state.selectedId || state.collections[0].id; if (!state.collections.some((collection) => collection.id === state.selectedId)) state.selectedId = state.collections[0].id; renderCollections(); await loadReport(); }
  async function loadReport() { const report = await request(`/api/prompt-intelligence/collections/${state.selectedId}/report`); state.report = report; renderReport(); }
  function metric(id, value, suffix = '') { $(id).textContent = value === null || value === undefined ? '—' : `${value}${suffix}`; }
  function renderReport() { const { collection, queries, summary } = state.report; $('#collection-title').textContent = collection.name; $('#collection-brand').textContent = collection.website ? `${collection.brand_name} · ${collection.website}` : collection.brand_name; $('#collection-meta').textContent = `${summary.tracked_count} prompt${summary.tracked_count === 1 ? '' : 's'} tracked`; metric('#tracked-prompts', summary.tracked_count); metric('#analysed-prompts', summary.analysed_count); metric('#average-visibility', summary.average_visibility, '%'); metric('#prompt-citation-rate', summary.citation_rate, '%'); renderQueries(queries); }
  function renderQueries(queries) { const engine = $('#engine-filter').value; const status = $('#status-filter').value; const filtered = queries.filter((query) => (engine === 'all' || query.engine === engine) && (status === 'all' || (status === 'cited' && query.result?.cited === 'Yes') || (status === 'gap' && (!query.result || query.result.cited === 'No')))); const root = $('#prompt-results'); if (!filtered.length) { root.innerHTML = `<p class="no-results">${queries.length ? 'No prompts match these filters.' : 'Add your first prompt above to begin tracking the answer landscape.'}</p>`; return; } root.innerHTML = filtered.map((query) => { const result = query.result; const outcome = result ? `<div class="result-data"><div class="result-stat">Visibility<strong>${result.visibility_score}%</strong></div><div class="result-copy"><strong>#${result.brand_position} · ${escapeHtml(result.cited === 'Yes' ? 'Brand cited' : 'Citation gap')}</strong>Leading brand: ${escapeHtml(result.leading_brand)}<br>${escapeHtml(result.answer_summary)}</div><div class="result-copy"><strong>Recommended action</strong>${escapeHtml(result.recommendation)}</div></div>` : '<p class="result-pending">This prompt is ready to analyse.</p>'; return `<article class="prompt-result"><div class="prompt-result-top"><div><h4>${escapeHtml(query.prompt)}</h4><div class="prompt-result-meta"><span>${escapeHtml(query.engine)}</span><span>${escapeHtml(query.intent)}</span>${result ? `<span class="${result.cited === 'Yes' ? 'cite-yes' : 'cite-no'}">${escapeHtml(result.cited === 'Yes' ? 'Cited' : 'Gap')}</span>` : ''}</div></div><div class="result-actions"><button class="mini-button analyse-query" data-id="${query.id}" type="button">${result ? 'Re-analyse' : 'Analyse'}</button><button class="mini-button remove delete-query" data-id="${query.id}" type="button">Remove</button></div></div>${outcome}</article>`; }).join(''); }
  async function analyse(queryId, button) { button.disabled = true; button.textContent = 'Analysing…'; try { const data = await request(`/api/prompt-intelligence/queries/${queryId}/analyse`, { method: 'POST' }); state.report = data.report; renderReport(); await loadCollections(state.selectedId); } catch (error) { notify(error.message); button.disabled = false; button.textContent = 'Analyse'; } }
  $('#open-collection-dialog').addEventListener('click', openDialog); $('#empty-new-collection').addEventListener('click', openDialog); $('#close-collection-dialog').addEventListener('click', () => ui.dialog.close());
  $('#collection-form').addEventListener('submit', async (event) => { event.preventDefault(); const button = $('#save-collection'); const error = $('#collection-error'); button.disabled = true; button.textContent = 'Creating…'; error.hidden = true; try { const data = await request('/api/prompt-intelligence/collections', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); ui.dialog.close(); await loadCollections(data.collection.id); } catch (err) { error.textContent = err.message; error.hidden = false; } finally { button.disabled = false; button.textContent = 'Create collection'; } });
  $('#prompt-form').addEventListener('submit', async (event) => { event.preventDefault(); const button = $('#add-prompt'); button.disabled = true; button.textContent = 'Adding…'; notify(''); try { const data = await request(`/api/prompt-intelligence/collections/${state.selectedId}/queries`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); event.currentTarget.reset(); await analyse(data.query_id, button); } catch (error) { notify(error.message); button.disabled = false; button.textContent = 'Add & analyse'; } });
  ui.picker.addEventListener('change', () => { state.selectedId = Number(ui.picker.value); loadReport().catch((error) => notify(error.message)); });
  $('#engine-filter').addEventListener('change', () => renderQueries(state.report.queries)); $('#status-filter').addEventListener('change', () => renderQueries(state.report.queries));
  $('#prompt-results').addEventListener('click', (event) => { const button = event.target.closest('button[data-id]'); if (!button) return; const id = button.dataset.id; if (button.classList.contains('analyse-query')) analyse(id, button); if (button.classList.contains('delete-query') && confirm('Remove this tracked prompt and its saved results?')) request(`/api/prompt-intelligence/queries/${id}`, { method: 'DELETE' }).then(() => loadReport()).catch((error) => notify(error.message)); });
  $('#delete-collection').addEventListener('click', () => { const collection = state.collections.find((item) => item.id === state.selectedId); if (!collection || !confirm(`Remove ${collection.name} and every saved prompt result?`)) return; request(`/api/prompt-intelligence/collections/${collection.id}`, { method: 'DELETE' }).then(() => { state.selectedId = null; loadCollections(); }).catch((error) => notify(error.message)); });
  $('#logout-button').addEventListener('click', () => request('/api/logout', { method: 'POST' }).then(() => location.assign('/')).catch((error) => notify(error.message)));
  loadCollections().catch((error) => { ui.loading.hidden = true; notify(error.message); });
});
