document.addEventListener('DOMContentLoaded', () => {
  const $ = (selector) => document.querySelector(selector);
  const state = { watchlists: [], selectedId: null, report: null };
  const ui = { loading: $('#visibility-loading'), empty: $('#watchlist-empty'), workspace: $('#visibility-workspace'), picker: $('#watchlist-picker'), notice: $('#visibility-notice'), dialog: $('#watchlist-dialog'), scan: $('#visibility-scan'), firstScan: $('#first-visibility-scan') };
  const escapeHtml = (value) => { const el = document.createElement('div'); el.textContent = value ?? ''; return el.innerHTML; };
  async function request(url, options) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (response.status === 401) { location.replace('/login'); throw new Error('Your session has ended.'); } if (!response.ok) throw new Error(data.error || 'Something went wrong.'); return data; }
  function notify(message) { ui.notice.textContent = message; ui.notice.hidden = !message; }
  function setScanning(busy) { ui.scan.disabled = busy; ui.scan.textContent = busy ? 'Scanning…' : 'Run visibility scan'; ui.firstScan.disabled = busy; ui.firstScan.textContent = busy ? 'Scanning…' : 'Run first scan'; }
  function openDialog() { $('#watchlist-error').hidden = true; $('#watchlist-form').reset(); ui.dialog.showModal(); }
  function fmtDate(value) { return new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }); }
  async function loadWatchlists(preferredId) { const data = await request('/api/visibility-tracking/watchlists'); state.watchlists = data.watchlists; ui.loading.hidden = true; if (!state.watchlists.length) { ui.empty.hidden = false; ui.workspace.hidden = true; return; } ui.empty.hidden = true; ui.workspace.hidden = false; state.selectedId = Number(preferredId) || state.selectedId || state.watchlists[0].id; if (!state.watchlists.some((watchlist) => watchlist.id === state.selectedId)) state.selectedId = state.watchlists[0].id; ui.picker.innerHTML = state.watchlists.map((watchlist) => `<option value="${watchlist.id}">${escapeHtml(watchlist.name)} · ${escapeHtml(watchlist.brand_name)}</option>`).join(''); ui.picker.value = state.selectedId; await loadReport(); }
  async function loadReport() { state.report = await request(`/api/visibility-tracking/watchlists/${state.selectedId}/report`); renderReport(); }
  function value(id, number, suffix = '') { $(id).textContent = number === null || number === undefined ? '—' : `${number}${suffix}`; }
  function renderReport() { const { watchlist, scan, engines, mentions, history } = state.report; $('#watchlist-title').textContent = watchlist.name; $('#watchlist-subtitle').textContent = `${watchlist.brand_name} · ${watchlist.topic}${watchlist.website ? ` · ${watchlist.website}` : ''}`; $('#watchlist-meta').textContent = scan ? `Last scan: ${fmtDate(scan.created_at)}` : 'Not scanned yet'; if (!scan) { $('#visibility-report').hidden = true; $('#visibility-report-empty').hidden = false; return; } $('#visibility-report').hidden = false; $('#visibility-report-empty').hidden = true; value('#visibility-score', scan.visibility_score); value('#mentions-found', scan.mentions_found); value('#citations-found', scan.citations_found); value('#competitor-mentions', scan.competitor_mentions); $('#visibility-summary').textContent = scan.summary; $('#visibility-current').textContent = `${scan.visibility_score}% current`; $('#visibility-chart').innerHTML = history.map((entry) => `<div class="trend-bar" style="height:${Math.max(18, entry.visibility_score)}%"><span>${entry.visibility_score}</span></div>`).join(''); $('#visibility-engines').innerHTML = engines.map((item) => { const change = item.change > 0 ? '+' : ''; return `<div class="engine-row"><strong>${escapeHtml(item.engine)}</strong><div class="engine-track"><span style="width:${item.visibility_score}%"></span></div><span class="engine-score">${item.visibility_score}% <small class="engine-change ${item.change < 0 ? 'down' : ''}">${change}${item.change}</small></span></div>`; }).join(''); renderMentions(mentions); }
  function renderMentions(mentions) { const filter = $('#mention-engine-filter').value; const visible = mentions.filter((item) => filter === 'all' || item.engine === filter); $('#mention-list').innerHTML = visible.length ? visible.map((item) => `<article class="mention-item"><div class="mention-engine">${escapeHtml(item.engine)}<span>${escapeHtml(item.appearance)}</span></div><p class="mention-query">${escapeHtml(item.query)}<small><span class="appearance-status ${item.sentiment.toLowerCase()}">${escapeHtml(item.sentiment)}</span> · ${item.cited === 'Yes' ? 'Brand cited' : 'No brand citation'} · Leading brand: ${escapeHtml(item.competitor)}</small></p><p class="mention-action"><strong>Recommended action</strong>${escapeHtml(item.action)}</p></article>`).join('') : '<p class="visibility-no-mentions">No appearances match this engine.</p>'; }
  async function scan() { setScanning(true); notify(''); try { const data = await request(`/api/visibility-tracking/watchlists/${state.selectedId}/scan`, { method: 'POST' }); state.report = data.report; renderReport(); await loadWatchlists(state.selectedId); } catch (error) { notify(error.message); } finally { setScanning(false); } }
  $('#open-watchlist-dialog').addEventListener('click', openDialog); $('#empty-new-watchlist').addEventListener('click', openDialog); $('#close-watchlist-dialog').addEventListener('click', () => ui.dialog.close());
  $('#watchlist-form').addEventListener('submit', async (event) => { event.preventDefault(); const button = $('#save-watchlist'); const error = $('#watchlist-error'); button.disabled = true; button.textContent = 'Creating…'; error.hidden = true; try { const data = await request('/api/visibility-tracking/watchlists', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); ui.dialog.close(); await loadWatchlists(data.watchlist.id); } catch (err) { error.textContent = err.message; error.hidden = false; } finally { button.disabled = false; button.textContent = 'Create watchlist'; } });
  ui.picker.addEventListener('change', () => { state.selectedId = Number(ui.picker.value); loadReport().catch((error) => notify(error.message)); }); ui.scan.addEventListener('click', scan); ui.firstScan.addEventListener('click', scan); $('#mention-engine-filter').addEventListener('change', () => renderMentions(state.report.mentions));
  $('#delete-watchlist').addEventListener('click', () => { const watchlist = state.watchlists.find((item) => item.id === state.selectedId); if (!watchlist || !confirm(`Remove ${watchlist.name} and every saved visibility scan?`)) return; request(`/api/visibility-tracking/watchlists/${watchlist.id}`, { method: 'DELETE' }).then(() => { state.selectedId = null; loadWatchlists(); }).catch((error) => notify(error.message)); });
  $('#logout-button').addEventListener('click', () => request('/api/logout', { method: 'POST' }).then(() => location.assign('/')).catch((error) => notify(error.message)));
  loadWatchlists().catch((error) => { ui.loading.hidden = true; notify(error.message); });
});
