"""tenancy: orgs, memberships, workspaces

Revision ID: 4ad49388142a
Revises: c3151ee83486
Create Date: 2026-08-30 01:47:55.534956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ad49388142a'
down_revision: Union[str, Sequence[str], None] = 'c3151ee83486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member', 'client_viewer')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'user_id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=False),
    sa.Column('domains', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('geo', sa.Text(), server_default='US', nullable=False),
    sa.Column('language', sa.Text(), server_default='en', nullable=False),
    sa.Column('kind', sa.Text(), server_default='project', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('project', 'pitch')", name='ck_workspace_kind'),
    sa.CheckConstraint("status IN ('active', 'soft_deleted')", name='ck_workspace_status'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspaces_org_active', 'workspaces', ['org_id'], unique=False, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.create_table('brand_aliases',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'alias')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('domains', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_competitor_name')
    )
    op.create_index(op.f('ix_competitors_workspace_id'), 'competitors', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_prompt_query_results_query_id'), table_name='prompt_query_results')
    op.drop_table('prompt_query_results')
    op.drop_index(op.f('ix_visibility_watchlists_user_id'), table_name='visibility_watchlists')
    op.drop_table('visibility_watchlists')
    op.drop_table('master_workspaces')
    op.drop_index(op.f('ix_analytics_prompts_run_id'), table_name='analytics_prompts')
    op.drop_table('analytics_prompts')
    op.drop_index(op.f('ix_prompt_collections_user_id'), table_name='prompt_collections')
    op.drop_table('prompt_collections')
    op.drop_index(op.f('ix_visibility_engine_results_scan_id'), table_name='visibility_engine_results')
    op.drop_table('visibility_engine_results')
    op.drop_index(op.f('ix_analytics_competitors_project_id'), table_name='analytics_competitors')
    op.drop_table('analytics_competitors')
    op.drop_index(op.f('ix_analytics_projects_user_id'), table_name='analytics_projects')
    op.drop_table('analytics_projects')
    op.drop_index(op.f('ix_analytics_engine_metrics_run_id'), table_name='analytics_engine_metrics')
    op.drop_table('analytics_engine_metrics')
    op.drop_index(op.f('ix_prompt_queries_collection_id'), table_name='prompt_queries')
    op.drop_table('prompt_queries')
    op.drop_index(op.f('ix_analytics_runs_project_id'), table_name='analytics_runs')
    op.drop_table('analytics_runs')
    op.drop_index(op.f('ix_visibility_scans_watchlist_id'), table_name='visibility_scans')
    op.drop_table('visibility_scans')
    op.drop_index(op.f('ix_visibility_mentions_scan_id'), table_name='visibility_mentions')
    op.drop_table('visibility_mentions')
    op.add_column('analytics_audit_jobs', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_analytics_audit_jobs_project_id'), table_name='analytics_audit_jobs')
    op.drop_index(op.f('ix_analytics_audit_jobs_user_id'), table_name='analytics_audit_jobs')
    op.create_index(op.f('ix_analytics_audit_jobs_workspace_id'), 'analytics_audit_jobs', ['workspace_id'], unique=False)
    op.drop_column('analytics_audit_jobs', 'user_id')
    op.drop_column('analytics_audit_jobs', 'project_id')
    op.add_column('analytics_content_opportunities', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_analytics_content_opportunities_project_id'), table_name='analytics_content_opportunities')
    op.create_index(op.f('ix_analytics_content_opportunities_workspace_id'), 'analytics_content_opportunities', ['workspace_id'], unique=False)
    op.drop_column('analytics_content_opportunities', 'project_id')
    op.add_column('analytics_prompt_scan_runs', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_analytics_prompt_scan_runs_project_id'), table_name='analytics_prompt_scan_runs')
    op.create_index(op.f('ix_analytics_prompt_scan_runs_workspace_id'), 'analytics_prompt_scan_runs', ['workspace_id'], unique=False)
    op.drop_column('analytics_prompt_scan_runs', 'project_id')
    op.add_column('analytics_rag_chunks', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_analytics_rag_chunks_project_id'), table_name='analytics_rag_chunks')
    op.create_index(op.f('ix_analytics_rag_chunks_workspace_id'), 'analytics_rag_chunks', ['workspace_id'], unique=False)
    op.drop_column('analytics_rag_chunks', 'project_id')
    op.add_column('analytics_rag_documents', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_analytics_rag_documents_project_id'), table_name='analytics_rag_documents')
    op.create_index(op.f('ix_analytics_rag_documents_workspace_id'), 'analytics_rag_documents', ['workspace_id'], unique=False)
    op.drop_column('analytics_rag_documents', 'project_id')
    op.add_column('analytics_rag_insights', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_analytics_rag_insights_project_id'), table_name='analytics_rag_insights')
    op.create_index(op.f('ix_analytics_rag_insights_workspace_id'), 'analytics_rag_insights', ['workspace_id'], unique=False)
    op.drop_column('analytics_rag_insights', 'project_id')
    op.add_column('analytics_scan_schedules', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('analytics_scan_schedules_project_id_key'), 'analytics_scan_schedules', type_='unique')
    op.create_unique_constraint('uq_analytics_scan_schedules_workspace_id', 'analytics_scan_schedules', ['workspace_id'])
    op.drop_column('analytics_scan_schedules', 'project_id')
    op.add_column('analytics_site_audits', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_analytics_site_audits_project_id'), table_name='analytics_site_audits')
    op.create_index(op.f('ix_analytics_site_audits_workspace_id'), 'analytics_site_audits', ['workspace_id'], unique=False)
    op.drop_column('analytics_site_audits', 'project_id')
    op.add_column('analytics_topics', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_analytics_topics_project_id'), table_name='analytics_topics')
    op.drop_constraint(op.f('uq_analytics_topic'), 'analytics_topics', type_='unique')
    op.create_unique_constraint('uq_analytics_topic', 'analytics_topics', ['workspace_id', 'name'])
    op.create_index(op.f('ix_analytics_topics_workspace_id'), 'analytics_topics', ['workspace_id'], unique=False)
    op.drop_column('analytics_topics', 'project_id')
    op.add_column('analytics_tracked_prompts', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_analytics_tracked_prompts_project_id'), table_name='analytics_tracked_prompts')
    op.create_index(op.f('ix_analytics_tracked_prompts_workspace_id'), 'analytics_tracked_prompts', ['workspace_id'], unique=False)
    op.drop_column('analytics_tracked_prompts', 'project_id')
    op.add_column('content_documents', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_content_documents_user_id'), table_name='content_documents')
    op.create_index(op.f('ix_content_documents_workspace_id'), 'content_documents', ['workspace_id'], unique=False)
    op.drop_column('content_documents', 'user_id')
    op.add_column('gsc_connections', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('gsc_connections_project_id_key'), 'gsc_connections', type_='unique')
    op.drop_index(op.f('ix_gsc_connections_user_id'), table_name='gsc_connections')
    op.create_unique_constraint('uq_gsc_connections_workspace_id', 'gsc_connections', ['workspace_id'])
    op.drop_column('gsc_connections', 'user_id')
    op.drop_column('gsc_connections', 'project_id')
    op.add_column('gsc_sync_runs', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_gsc_sync_runs_project_id'), table_name='gsc_sync_runs')
    op.create_index(op.f('ix_gsc_sync_runs_workspace_id'), 'gsc_sync_runs', ['workspace_id'], unique=False)
    op.drop_column('gsc_sync_runs', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsc_sync_runs', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_gsc_sync_runs_workspace_id'), table_name='gsc_sync_runs')
    op.create_index(op.f('ix_gsc_sync_runs_project_id'), 'gsc_sync_runs', ['project_id'], unique=False)
    op.drop_column('gsc_sync_runs', 'workspace_id')
    op.add_column('gsc_connections', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('gsc_connections', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_gsc_connections_workspace_id', 'gsc_connections', type_='unique')
    op.create_index(op.f('ix_gsc_connections_user_id'), 'gsc_connections', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('gsc_connections_project_id_key'), 'gsc_connections', ['project_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('gsc_connections', 'workspace_id')
    op.add_column('content_documents', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_content_documents_workspace_id'), table_name='content_documents')
    op.create_index(op.f('ix_content_documents_user_id'), 'content_documents', ['user_id'], unique=False)
    op.drop_column('content_documents', 'workspace_id')
    op.add_column('analytics_tracked_prompts', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_tracked_prompts_workspace_id'), table_name='analytics_tracked_prompts')
    op.create_index(op.f('ix_analytics_tracked_prompts_project_id'), 'analytics_tracked_prompts', ['project_id'], unique=False)
    op.drop_column('analytics_tracked_prompts', 'workspace_id')
    op.add_column('analytics_topics', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_topics_workspace_id'), table_name='analytics_topics')
    op.drop_constraint('uq_analytics_topic', 'analytics_topics', type_='unique')
    op.create_unique_constraint(op.f('uq_analytics_topic'), 'analytics_topics', ['project_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_analytics_topics_project_id'), 'analytics_topics', ['project_id'], unique=False)
    op.drop_column('analytics_topics', 'workspace_id')
    op.add_column('analytics_site_audits', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_site_audits_workspace_id'), table_name='analytics_site_audits')
    op.create_index(op.f('ix_analytics_site_audits_project_id'), 'analytics_site_audits', ['project_id'], unique=False)
    op.drop_column('analytics_site_audits', 'workspace_id')
    op.add_column('analytics_scan_schedules', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_analytics_scan_schedules_workspace_id', 'analytics_scan_schedules', type_='unique')
    op.create_unique_constraint(op.f('analytics_scan_schedules_project_id_key'), 'analytics_scan_schedules', ['project_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('analytics_scan_schedules', 'workspace_id')
    op.add_column('analytics_rag_insights', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_rag_insights_workspace_id'), table_name='analytics_rag_insights')
    op.create_index(op.f('ix_analytics_rag_insights_project_id'), 'analytics_rag_insights', ['project_id'], unique=False)
    op.drop_column('analytics_rag_insights', 'workspace_id')
    op.add_column('analytics_rag_documents', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_rag_documents_workspace_id'), table_name='analytics_rag_documents')
    op.create_index(op.f('ix_analytics_rag_documents_project_id'), 'analytics_rag_documents', ['project_id'], unique=False)
    op.drop_column('analytics_rag_documents', 'workspace_id')
    op.add_column('analytics_rag_chunks', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_rag_chunks_workspace_id'), table_name='analytics_rag_chunks')
    op.create_index(op.f('ix_analytics_rag_chunks_project_id'), 'analytics_rag_chunks', ['project_id'], unique=False)
    op.drop_column('analytics_rag_chunks', 'workspace_id')
    op.add_column('analytics_prompt_scan_runs', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_prompt_scan_runs_workspace_id'), table_name='analytics_prompt_scan_runs')
    op.create_index(op.f('ix_analytics_prompt_scan_runs_project_id'), 'analytics_prompt_scan_runs', ['project_id'], unique=False)
    op.drop_column('analytics_prompt_scan_runs', 'workspace_id')
    op.add_column('analytics_content_opportunities', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_content_opportunities_workspace_id'), table_name='analytics_content_opportunities')
    op.create_index(op.f('ix_analytics_content_opportunities_project_id'), 'analytics_content_opportunities', ['project_id'], unique=False)
    op.drop_column('analytics_content_opportunities', 'workspace_id')
    op.add_column('analytics_audit_jobs', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('analytics_audit_jobs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analytics_audit_jobs_workspace_id'), table_name='analytics_audit_jobs')
    op.create_index(op.f('ix_analytics_audit_jobs_user_id'), 'analytics_audit_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_analytics_audit_jobs_project_id'), 'analytics_audit_jobs', ['project_id'], unique=False)
    op.drop_column('analytics_audit_jobs', 'workspace_id')
    op.create_table('visibility_mentions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('engine', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('appearance', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('sentiment', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('cited', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('competitor', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('visibility_mentions_pkey'))
    )
    op.create_index(op.f('ix_visibility_mentions_scan_id'), 'visibility_mentions', ['scan_id'], unique=False)
    op.create_table('visibility_scans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visibility_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mentions_found', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('citations_found', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competitor_mentions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('visibility_scans_pkey'))
    )
    op.create_index(op.f('ix_visibility_scans_watchlist_id'), 'visibility_scans', ['watchlist_id'], unique=False)
    op.create_table('analytics_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visibility_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mention_rate', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('citation_rate', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('share_of_voice', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_runs_pkey'))
    )
    op.create_index(op.f('ix_analytics_runs_project_id'), 'analytics_runs', ['project_id'], unique=False)
    op.create_table('prompt_queries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engine', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_queries_pkey'))
    )
    op.create_index(op.f('ix_prompt_queries_collection_id'), 'prompt_queries', ['collection_id'], unique=False)
    op.create_table('analytics_engine_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('engine', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('visibility_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mention_rate', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('citations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_engine_metrics_pkey'))
    )
    op.create_index(op.f('ix_analytics_engine_metrics_run_id'), 'analytics_engine_metrics', ['run_id'], unique=False)
    op.create_table('analytics_projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('website_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('brand_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_projects_pkey'))
    )
    op.create_index(op.f('ix_analytics_projects_user_id'), 'analytics_projects', ['user_id'], unique=False)
    op.create_table('analytics_competitors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_competitors_pkey')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_analytics_competitor'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_analytics_competitors_project_id'), 'analytics_competitors', ['project_id'], unique=False)
    op.create_table('visibility_engine_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('engine', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('visibility_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mentions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('citations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('visibility_engine_results_pkey'))
    )
    op.create_index(op.f('ix_visibility_engine_results_scan_id'), 'visibility_engine_results', ['scan_id'], unique=False)
    op.create_table('prompt_collections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_collections_pkey'))
    )
    op.create_index(op.f('ix_prompt_collections_user_id'), 'prompt_collections', ['user_id'], unique=False)
    op.create_table('analytics_prompts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cited', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('leading_brand', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('opportunity', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_prompts_pkey'))
    )
    op.create_index(op.f('ix_analytics_prompts_run_id'), 'analytics_prompts', ['run_id'], unique=False)
    op.create_table('master_workspaces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('analytics_project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visibility_watchlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('master_workspaces_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('master_workspaces_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('visibility_watchlists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('visibility_watchlists_pkey'))
    )
    op.create_index(op.f('ix_visibility_watchlists_user_id'), 'visibility_watchlists', ['user_id'], unique=False)
    op.create_table('prompt_query_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visibility_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cited', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('leading_brand', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('answer_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_query_results_pkey'))
    )
    op.create_index(op.f('ix_prompt_query_results_query_id'), 'prompt_query_results', ['query_id'], unique=False)
    op.drop_index(op.f('ix_competitors_workspace_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_table('brand_aliases')
    op.drop_index('ix_workspaces_org_active', table_name='workspaces', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.drop_table('workspaces')
    op.drop_table('memberships')
    op.drop_table('organizations')
    # ### end Alembic commands ###
