"""metrics_daily and run_type

Revision ID: 88b18811897c
Revises: 8add7b9a3753
Create Date: 2026-08-30 15:51:56.167474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b18811897c'
down_revision: Union[str, Sequence[str], None] = '8add7b9a3753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_daily',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=True),
    sa.Column('visibility_score', sa.Float(), nullable=True),
    sa.Column('mention_rate', sa.Float(), nullable=True),
    sa.Column('position_score', sa.Float(), nullable=True),
    sa.Column('citation_rate', sa.Float(), nullable=True),
    sa.Column('sov', sa.Float(), nullable=True),
    sa.Column('sentiment_index', sa.Float(), nullable=True),
    sa.Column('answer_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False)
    )
    op.create_index('uq_metrics_daily_key', 'metrics_daily', ['workspace_id', 'date', sa.literal_column('coalesce(engine_id, -1)')], unique=True)
    op.add_column('analytics_audit_jobs', sa.Column('run_type', sa.Text(), server_default='scheduled', nullable=False))
    op.add_column('analytics_prompt_scan_runs', sa.Column('run_type', sa.Text(), server_default='scheduled', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics_prompt_scan_runs', 'run_type')
    op.drop_column('analytics_audit_jobs', 'run_type')
    op.drop_index('uq_metrics_daily_key', table_name='metrics_daily')
    op.drop_table('metrics_daily')
    # ### end Alembic commands ###
