"""extraction v2: extractions, mentions, citation category

Revision ID: 8add7b9a3753
Revises: f079dba33e60
Create Date: 2026-08-30 15:33:53.671919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8add7b9a3753'
down_revision: Union[str, Sequence[str], None] = 'f079dba33e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('extractor_version', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('brand_rank', sa.Integer(), nullable=True),
    sa.Column('brand_cited', sa.Boolean(), nullable=False),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('sentiment_conf', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_answer_id'), 'extractions', ['answer_id'], unique=False)
    op.create_index('uq_extractions_current_answer', 'extractions', ['answer_id'], unique=True, sqlite_where=sa.text('is_current'), postgresql_where=sa.text('is_current'))
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('char_offset', sa.Integer(), nullable=False),
    sa.CheckConstraint("entity_type IN ('brand', 'competitor')", name='ck_mentions_entity_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentions_extraction_id'), 'mentions', ['extraction_id'], unique=False)
    op.add_column('analytics_answer_sources', sa.Column('category', sa.Text(), nullable=True))
    op.drop_column('analytics_provider_answers', 'source_present')
    op.drop_column('analytics_provider_answers', 'brand_mentioned')
    op.drop_column('analytics_provider_answers', 'best_source_rank')
    op.drop_column('analytics_provider_answers', 'brand_cited')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_provider_answers', sa.Column('brand_cited', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('analytics_provider_answers', sa.Column('best_source_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('analytics_provider_answers', sa.Column('brand_mentioned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('analytics_provider_answers', sa.Column('source_present', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('analytics_answer_sources', 'category')
    op.drop_index(op.f('ix_mentions_extraction_id'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index('uq_extractions_current_answer', table_name='extractions', sqlite_where=sa.text('is_current'), postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_extractions_answer_id'), table_name='extractions')
    op.drop_table('extractions')
    # ### end Alembic commands ###
