"""engines table and engine_id on answers

Revision ID: bd9feb6cf5bc
Revises: 88b18811897c
Create Date: 2026-08-30 23:52:18.256689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9feb6cf5bc'
down_revision: Union[str, Sequence[str], None] = '88b18811897c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('adapter_version', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint("source_type IN ('api', 'scraper', 'serp_vendor')", name='ck_engines_source_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.add_column('analytics_provider_answers', sa.Column('engine_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_analytics_provider_answers_engine_id'), 'analytics_provider_answers', ['engine_id'], unique=False)
    op.create_foreign_key(None, 'analytics_provider_answers', 'engines', ['engine_id'], ['id'])
    # ### end Alembic commands ###

    # Seed the one engine that exists today. From here, adding an engine is a row
    # plus a module - never a migration.
    op.execute(sa.text(
        "INSERT INTO engines (key, display_name, source_type, adapter_version, enabled) "
        "VALUES ('perplexity', 'Perplexity', 'api', '2026.08.1', true)"
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analytics_provider_answers', type_='foreignkey')
    op.drop_index(op.f('ix_analytics_provider_answers_engine_id'), table_name='analytics_provider_answers')
    op.drop_column('analytics_provider_answers', 'engine_id')
    op.drop_table('engines')
    # ### end Alembic commands ###
