"""baseline schema

Revision ID: c3151ee83486
Revises: 
Create Date: 2026-08-30 01:09:13.330445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3151ee83486'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_answer_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('published_at', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_answer_sources_answer_id'), 'analytics_answer_sources', ['answer_id'], unique=False)
    op.create_table('analytics_audit_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_audit_findings_audit_id'), 'analytics_audit_findings', ['audit_id'], unique=False)
    op.create_index(op.f('ix_analytics_audit_findings_page_id'), 'analytics_audit_findings', ['page_id'], unique=False)
    op.create_table('analytics_audit_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_audit_jobs_project_id'), 'analytics_audit_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_analytics_audit_jobs_user_id'), 'analytics_audit_jobs', ['user_id'], unique=False)
    op.create_table('analytics_audit_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('fetched', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('headings_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('schema_blocks', sa.Integer(), nullable=False),
    sa.Column('canonical', sa.String(length=2048), nullable=True),
    sa.Column('noindex', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('internal_links', sa.Integer(), nullable=False),
    sa.Column('external_links', sa.Integer(), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('metadata_score', sa.Integer(), nullable=True),
    sa.Column('content_score', sa.Integer(), nullable=True),
    sa.Column('crawlability_score', sa.Integer(), nullable=True),
    sa.Column('structured_data_score', sa.Integer(), nullable=True),
    sa.Column('issues_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'url', name='uq_analytics_audit_page')
    )
    op.create_index(op.f('ix_analytics_audit_pages_audit_id'), 'analytics_audit_pages', ['audit_id'], unique=False)
    op.create_table('analytics_competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_analytics_competitor')
    )
    op.create_index(op.f('ix_analytics_competitors_project_id'), 'analytics_competitors', ['project_id'], unique=False)
    op.create_table('analytics_content_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_content_opportunities_project_id'), 'analytics_content_opportunities', ['project_id'], unique=False)
    op.create_index(op.f('ix_analytics_content_opportunities_scan_run_id'), 'analytics_content_opportunities', ['scan_run_id'], unique=False)
    op.create_table('analytics_engine_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('visibility_score', sa.Integer(), nullable=False),
    sa.Column('mention_rate', sa.Integer(), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_engine_metrics_run_id'), 'analytics_engine_metrics', ['run_id'], unique=False)
    op.create_table('analytics_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_projects_user_id'), 'analytics_projects', ['user_id'], unique=False)
    op.create_table('analytics_prompt_scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=True),
    sa.Column('competitor_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('mention_rate', sa.Float(), nullable=True),
    sa.Column('citation_rate', sa.Float(), nullable=True),
    sa.Column('source_presence_rate', sa.Float(), nullable=True),
    sa.Column('share_of_voice', sa.Float(), nullable=True),
    sa.Column('recommendation_summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_prompt_scan_runs_job_id'), 'analytics_prompt_scan_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_analytics_prompt_scan_runs_project_id'), 'analytics_prompt_scan_runs', ['project_id'], unique=False)
    op.create_table('analytics_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('cited', sa.String(length=8), nullable=False),
    sa.Column('leading_brand', sa.String(length=150), nullable=False),
    sa.Column('opportunity', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_prompts_run_id'), 'analytics_prompts', ['run_id'], unique=False)
    op.create_table('analytics_provider_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('prompt_intent', sa.String(length=80), nullable=True),
    sa.Column('topic_name', sa.String(length=180), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('search_request_id', sa.String(length=255), nullable=True),
    sa.Column('answer_request_id', sa.String(length=255), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=True),
    sa.Column('brand_cited', sa.Boolean(), nullable=True),
    sa.Column('source_present', sa.Boolean(), nullable=True),
    sa.Column('best_source_rank', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_provider_answers_prompt_id'), 'analytics_provider_answers', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_analytics_provider_answers_scan_run_id'), 'analytics_provider_answers', ['scan_run_id'], unique=False)
    op.create_table('analytics_rag_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_analytics_rag_document_chunk')
    )
    op.create_index(op.f('ix_analytics_rag_chunks_audit_id'), 'analytics_rag_chunks', ['audit_id'], unique=False)
    op.create_index(op.f('ix_analytics_rag_chunks_document_id'), 'analytics_rag_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_analytics_rag_chunks_project_id'), 'analytics_rag_chunks', ['project_id'], unique=False)
    op.create_table('analytics_rag_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'page_id', name='uq_analytics_rag_document_page')
    )
    op.create_index(op.f('ix_analytics_rag_documents_audit_id'), 'analytics_rag_documents', ['audit_id'], unique=False)
    op.create_index(op.f('ix_analytics_rag_documents_page_id'), 'analytics_rag_documents', ['page_id'], unique=False)
    op.create_index(op.f('ix_analytics_rag_documents_project_id'), 'analytics_rag_documents', ['project_id'], unique=False)
    op.create_table('analytics_rag_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('evidence_refs', sa.Text(), nullable=False),
    sa.Column('retrieved_chunk_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_rag_insights_audit_id'), 'analytics_rag_insights', ['audit_id'], unique=False)
    op.create_index(op.f('ix_analytics_rag_insights_project_id'), 'analytics_rag_insights', ['project_id'], unique=False)
    op.create_table('analytics_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('visibility_score', sa.Integer(), nullable=False),
    sa.Column('mention_rate', sa.Integer(), nullable=False),
    sa.Column('citation_rate', sa.Integer(), nullable=False),
    sa.Column('share_of_voice', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_runs_project_id'), 'analytics_runs', ['project_id'], unique=False)
    op.create_table('analytics_scan_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('analytics_site_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('start_url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('pages_audited', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('metadata_score', sa.Integer(), nullable=True),
    sa.Column('content_score', sa.Integer(), nullable=True),
    sa.Column('crawlability_score', sa.Integer(), nullable=True),
    sa.Column('structured_data_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_site_audits_job_id'), 'analytics_site_audits', ['job_id'], unique=False)
    op.create_index(op.f('ix_analytics_site_audits_project_id'), 'analytics_site_audits', ['project_id'], unique=False)
    op.create_table('analytics_sitemaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('urls_discovered', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_sitemaps_audit_id'), 'analytics_sitemaps', ['audit_id'], unique=False)
    op.create_table('analytics_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_analytics_topic')
    )
    op.create_index(op.f('ix_analytics_topics_project_id'), 'analytics_topics', ['project_id'], unique=False)
    op.create_table('analytics_tracked_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_tracked_prompts_project_id'), 'analytics_tracked_prompts', ['project_id'], unique=False)
    op.create_index(op.f('ix_analytics_tracked_prompts_topic_id'), 'analytics_tracked_prompts', ['topic_id'], unique=False)
    op.create_table('app_metadata',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('tone', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=False),
    sa.Column('meta_description', sa.String(length=320), nullable=False),
    sa.Column('outline', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_documents_user_id'), 'content_documents', ['user_id'], unique=False)
    op.create_table('gsc_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('granted_scopes', sa.Text(), nullable=True),
    sa.Column('selected_property', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_gsc_connections_user_id'), 'gsc_connections', ['user_id'], unique=False)
    op.create_table('gsc_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('site_url', sa.String(length=2048), nullable=False),
    sa.Column('permission_level', sa.String(length=80), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'site_url', name='uq_gsc_connection_property')
    )
    op.create_index(op.f('ix_gsc_properties_connection_id'), 'gsc_properties', ['connection_id'], unique=False)
    op.create_table('gsc_query_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('page', sa.String(length=2048), nullable=True),
    sa.Column('clicks', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Float(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsc_query_rows_sync_run_id'), 'gsc_query_rows', ['sync_run_id'], unique=False)
    op.create_table('gsc_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('property_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('rows_saved', sa.Integer(), nullable=False),
    sa.Column('data_state', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsc_sync_runs_connection_id'), 'gsc_sync_runs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_gsc_sync_runs_project_id'), 'gsc_sync_runs', ['project_id'], unique=False)
    op.create_table('master_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.String(length=200), nullable=False),
    sa.Column('analytics_project_id', sa.Integer(), nullable=False),
    sa.Column('visibility_watchlist_id', sa.Integer(), nullable=False),
    sa.Column('prompt_collection_id', sa.Integer(), nullable=False),
    sa.Column('content_document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('prompt_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_collections_user_id'), 'prompt_collections', ['user_id'], unique=False)
    op.create_table('prompt_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('intent', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_queries_collection_id'), 'prompt_queries', ['collection_id'], unique=False)
    op.create_table('prompt_query_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('visibility_score', sa.Integer(), nullable=False),
    sa.Column('brand_position', sa.Integer(), nullable=False),
    sa.Column('cited', sa.String(length=8), nullable=False),
    sa.Column('leading_brand', sa.String(length=150), nullable=False),
    sa.Column('answer_summary', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_query_results_query_id'), 'prompt_query_results', ['query_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('visibility_engine_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('visibility_score', sa.Integer(), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_engine_results_scan_id'), 'visibility_engine_results', ['scan_id'], unique=False)
    op.create_table('visibility_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('appearance', sa.String(length=80), nullable=False),
    sa.Column('sentiment', sa.String(length=30), nullable=False),
    sa.Column('cited', sa.String(length=8), nullable=False),
    sa.Column('competitor', sa.String(length=150), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_mentions_scan_id'), 'visibility_mentions', ['scan_id'], unique=False)
    op.create_table('visibility_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('visibility_score', sa.Integer(), nullable=False),
    sa.Column('mentions_found', sa.Integer(), nullable=False),
    sa.Column('citations_found', sa.Integer(), nullable=False),
    sa.Column('competitor_mentions', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_scans_watchlist_id'), 'visibility_scans', ['watchlist_id'], unique=False)
    op.create_table('visibility_watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_watchlists_user_id'), 'visibility_watchlists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visibility_watchlists_user_id'), table_name='visibility_watchlists')
    op.drop_table('visibility_watchlists')
    op.drop_index(op.f('ix_visibility_scans_watchlist_id'), table_name='visibility_scans')
    op.drop_table('visibility_scans')
    op.drop_index(op.f('ix_visibility_mentions_scan_id'), table_name='visibility_mentions')
    op.drop_table('visibility_mentions')
    op.drop_index(op.f('ix_visibility_engine_results_scan_id'), table_name='visibility_engine_results')
    op.drop_table('visibility_engine_results')
    op.drop_table('users')
    op.drop_index(op.f('ix_prompt_query_results_query_id'), table_name='prompt_query_results')
    op.drop_table('prompt_query_results')
    op.drop_index(op.f('ix_prompt_queries_collection_id'), table_name='prompt_queries')
    op.drop_table('prompt_queries')
    op.drop_index(op.f('ix_prompt_collections_user_id'), table_name='prompt_collections')
    op.drop_table('prompt_collections')
    op.drop_table('master_workspaces')
    op.drop_index(op.f('ix_gsc_sync_runs_project_id'), table_name='gsc_sync_runs')
    op.drop_index(op.f('ix_gsc_sync_runs_connection_id'), table_name='gsc_sync_runs')
    op.drop_table('gsc_sync_runs')
    op.drop_index(op.f('ix_gsc_query_rows_sync_run_id'), table_name='gsc_query_rows')
    op.drop_table('gsc_query_rows')
    op.drop_index(op.f('ix_gsc_properties_connection_id'), table_name='gsc_properties')
    op.drop_table('gsc_properties')
    op.drop_index(op.f('ix_gsc_connections_user_id'), table_name='gsc_connections')
    op.drop_table('gsc_connections')
    op.drop_index(op.f('ix_content_documents_user_id'), table_name='content_documents')
    op.drop_table('content_documents')
    op.drop_table('contacts')
    op.drop_table('app_metadata')
    op.drop_index(op.f('ix_analytics_tracked_prompts_topic_id'), table_name='analytics_tracked_prompts')
    op.drop_index(op.f('ix_analytics_tracked_prompts_project_id'), table_name='analytics_tracked_prompts')
    op.drop_table('analytics_tracked_prompts')
    op.drop_index(op.f('ix_analytics_topics_project_id'), table_name='analytics_topics')
    op.drop_table('analytics_topics')
    op.drop_index(op.f('ix_analytics_sitemaps_audit_id'), table_name='analytics_sitemaps')
    op.drop_table('analytics_sitemaps')
    op.drop_index(op.f('ix_analytics_site_audits_project_id'), table_name='analytics_site_audits')
    op.drop_index(op.f('ix_analytics_site_audits_job_id'), table_name='analytics_site_audits')
    op.drop_table('analytics_site_audits')
    op.drop_table('analytics_scan_schedules')
    op.drop_index(op.f('ix_analytics_runs_project_id'), table_name='analytics_runs')
    op.drop_table('analytics_runs')
    op.drop_index(op.f('ix_analytics_rag_insights_project_id'), table_name='analytics_rag_insights')
    op.drop_index(op.f('ix_analytics_rag_insights_audit_id'), table_name='analytics_rag_insights')
    op.drop_table('analytics_rag_insights')
    op.drop_index(op.f('ix_analytics_rag_documents_project_id'), table_name='analytics_rag_documents')
    op.drop_index(op.f('ix_analytics_rag_documents_page_id'), table_name='analytics_rag_documents')
    op.drop_index(op.f('ix_analytics_rag_documents_audit_id'), table_name='analytics_rag_documents')
    op.drop_table('analytics_rag_documents')
    op.drop_index(op.f('ix_analytics_rag_chunks_project_id'), table_name='analytics_rag_chunks')
    op.drop_index(op.f('ix_analytics_rag_chunks_document_id'), table_name='analytics_rag_chunks')
    op.drop_index(op.f('ix_analytics_rag_chunks_audit_id'), table_name='analytics_rag_chunks')
    op.drop_table('analytics_rag_chunks')
    op.drop_index(op.f('ix_analytics_provider_answers_scan_run_id'), table_name='analytics_provider_answers')
    op.drop_index(op.f('ix_analytics_provider_answers_prompt_id'), table_name='analytics_provider_answers')
    op.drop_table('analytics_provider_answers')
    op.drop_index(op.f('ix_analytics_prompts_run_id'), table_name='analytics_prompts')
    op.drop_table('analytics_prompts')
    op.drop_index(op.f('ix_analytics_prompt_scan_runs_project_id'), table_name='analytics_prompt_scan_runs')
    op.drop_index(op.f('ix_analytics_prompt_scan_runs_job_id'), table_name='analytics_prompt_scan_runs')
    op.drop_table('analytics_prompt_scan_runs')
    op.drop_index(op.f('ix_analytics_projects_user_id'), table_name='analytics_projects')
    op.drop_table('analytics_projects')
    op.drop_index(op.f('ix_analytics_engine_metrics_run_id'), table_name='analytics_engine_metrics')
    op.drop_table('analytics_engine_metrics')
    op.drop_index(op.f('ix_analytics_content_opportunities_scan_run_id'), table_name='analytics_content_opportunities')
    op.drop_index(op.f('ix_analytics_content_opportunities_project_id'), table_name='analytics_content_opportunities')
    op.drop_table('analytics_content_opportunities')
    op.drop_index(op.f('ix_analytics_competitors_project_id'), table_name='analytics_competitors')
    op.drop_table('analytics_competitors')
    op.drop_index(op.f('ix_analytics_audit_pages_audit_id'), table_name='analytics_audit_pages')
    op.drop_table('analytics_audit_pages')
    op.drop_index(op.f('ix_analytics_audit_jobs_user_id'), table_name='analytics_audit_jobs')
    op.drop_index(op.f('ix_analytics_audit_jobs_project_id'), table_name='analytics_audit_jobs')
    op.drop_table('analytics_audit_jobs')
    op.drop_index(op.f('ix_analytics_audit_findings_page_id'), table_name='analytics_audit_findings')
    op.drop_index(op.f('ix_analytics_audit_findings_audit_id'), table_name='analytics_audit_findings')
    op.drop_table('analytics_audit_findings')
    op.drop_index(op.f('ix_analytics_answer_sources_answer_id'), table_name='analytics_answer_sources')
    op.drop_table('analytics_answer_sources')
    # ### end Alembic commands ###
