"""usage ledger and org spend ceiling

Revision ID: f079dba33e60
Revises: 4ad49388142a
Create Date: 2026-08-30 03:09:17.971823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f079dba33e60'
down_revision: Union[str, Sequence[str], None] = '4ad49388142a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('engine_query', 'extraction', 'agent', 'content', 'crawl')", name='ck_usage_ledger_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_ledger_org_created', 'usage_ledger', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_ledger_org_id'), 'usage_ledger', ['org_id'], unique=False)
    op.add_column('organizations', sa.Column('monthly_cost_ceiling_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'monthly_cost_ceiling_usd')
    op.drop_index(op.f('ix_usage_ledger_org_id'), table_name='usage_ledger')
    op.drop_index('ix_usage_ledger_org_created', table_name='usage_ledger')
    op.drop_table('usage_ledger')
    # ### end Alembic commands ###
